export const suggestedCategories = [
  "Women Clothes",
  "Men Clothes",
  "Beauty",
  "Health",
  "Fashion Accessories",
  "Home & Living",
  "Men Shoes",
  "Women Shoes",
  "Men Bags",
  "Women Bags",
  "Watches",
  "Electronics",
  "Computers & Accessories",
  "Drinks",
  "Bread & Pastries",
  "Sports & Outdoors",
  "Stationery",
  "Bookes & Magazines",
  "Automobile Parts & Accessories",
  "Motorcycle Parts & Accessories",
  "Pets",
  "Baby & Kids",
  "Travel & Luggage",
]
